### ISSUE TITLE
Arduino ide 1.8.10 uploading the update from October 2019 does not work matrix keypad

### ISSUE THREAD

**Issue by qulet** [bdurbrow/grbl-Mega#19]
When I go back to the previous version everything is ok.
What can I do to make the 4x4 key matrix enable?

**Comment by qulet** [comment]
must be #define UI_KEYPAD_ORIENTATION 0
I had #define UI_KEYPAD_ORIENTATION 180

**Comment by bdurbrow** [comment]
Oops... The default was supposed to be zero... I don’t know how that made it into the version that got pushed to github; but I’ll fix it in the next update.
